### ISSUE TITLE
enableLiveReload({strategy: 'react-hmr'}); doesn't work for me.

### ISSUE THREAD

**Issue by mnemanja** [electron-userland/electron-compile#273]
node v6.11.3
npm v3.10.10
yarn v1.2.1
os windows 10

Hello,

I've initialized the `electron-forge` app and tried testing the hot reload, but nothing happens.
If I remove the "strategy" from the `enableLiveReload`, then the page refresh happens, but that reloads the whole state.

Now, while debugging this behavior I've noticed that when making changes the reload does occur on the script level: each time `HMR sent to all windows!` gets reported after the change, but no visual changes are applied.

Second clue: I have a console.log in the **app.jsx** file and when I'm changing any part of the application, except **app.jsx**, the console.log reports to the devTool's console.
Then I went and changed the content of the console.log statement - nothing happened, and after making changes to some other file, the console.log did get triggered (as described above) but the state of the console.log in question did not get updated in the devTool's console.

My `.compilerc` file looks like this (default):
```
 {
  "env": {
    "development": {
      "application/javascript": {
        "presets": [
          ["env", { "targets": { "electron": "1.6.0" } }],
          "react"
        ],
        "plugins": ["transform-async-to-generator", "transform-es2015-classes", "react-hot-loader/babel"],
        "sourceMaps": "inline"
      }
    },
    "production": {
      "application/javascript": {
        "presets": [
          ["env", { "targets": { "electron": "1.6.0" } }],
          "react"
        ],
        "plugins": ["transform-async-to-generator", "transform-es2015-classes"],
        "sourceMaps": "none"
      }
    }
  }
}
```

and adding `"es2017-node6"` reports an error:
```
> rm2-react@1.0.0 start C:\www\rm2-react
> electron-forge start

√ Checking your system
√ Locating Application
√ Preparing native dependencies
√ Launching Application

App threw an error during load
Error: Couldn't find preset "es2017-node6" relative to directory "C:\\www\\rm2-react\\src"
    at C:\www\rm2-react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (C:\www\rm2-react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\www\rm2-react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\www\rm2-react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\www\rm2-react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\www\rm2-react\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\www\rm2-react\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\www\rm2-react\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at BabelCompiler.compileSync (C:\www\rm2-react\node_modules\electron-compilers\lib\js\babel.js:81:26)
```
```
{
  "env": {
    "development": {
      "application/javascript": {
        "presets": [
          ["env", { "targets": { "electron": "1.6.0" } }],
          "react", "es2017-node6"
        ],
        "plugins": ["transform-async-to-generator", "transform-es2015-classes", "react-hot-loader/babel"],
        "sourceMaps": "inline"
      }
    },
    "production": {
      "application/javascript": {
        "presets": [
          ["env", { "targets": { "electron": "1.6.0" } }],
          "react"
        ],
        "plugins": ["transform-async-to-generator", "transform-es2015-classes"],
        "sourceMaps": "none"
      }
    }
  }
}
```

**Comment by mnemanja** [comment]
This was my bad, I've removed the **app.jsx** call from the `render` method.

Returning it back made HMR work again.

**Comment by mnemanja** [comment]
Changing **app.jsx** does update the view, but the previously mentioned behavior is still present when changing the **css** where changes do not get applied to the view. I can see the changes only after manual refresh.

Same goes for the **index.html**, but this is not that important since this file will not be changed often.

**Comment by skrichten** [comment]
+1 same issue here using Less

**Comment by bradharms** [comment]
Same issue using sass.

**Comment by nphi1212** [comment]
+1 with SASS

**Comment by Glinkis** [comment]
+1 with SCSS
