### ISSUE TITLE
enableLiveReload not working

### ISSUE THREAD

**Issue by kneumei** [electron-userland/electron-compile#289]
Whenever I try to use `enableLiveReload()`, I get a stack trace like this:

```
App threw an error during load
TypeError: global.globalCompilerHost.listenToCompileEvents(...).filter is not a function
    at enableLiveReloadNaive (C:\Users\Kyle\Documents\Github\electron-quick-start\node_modules\electron-compile\lib\live-reload.js:72:76)
    at enableLiveReload (C:\Users\Kyle\Documents\Github\electron-quick-start\node_modules\electron-compile\lib\live-reload.js:49:7)
    at enableLiveReload (C:\Users\Kyle\Documents\Github\electron-quick-start\node_modules\electron-compile\lib\index.js:35:12)
    at Object.<anonymous> (C:\Users\Kyle\Documents\Github\electron-quick-start\main.js:4:1)
    at Object.<anonymous> (C:\Users\Kyle\Documents\Github\electron-quick-start\main.js:67:3)
```

Steps to reproduce:
1. `git clone https://github.com/electron/electron-quick-start.git`
2. Edit package.json. change `"electron": "~1.7.8"` to `"electron-prebuilt-compile": "1.8.2-beta.3"`
3. `npm install`
4. Edit main.js. Set first to lines to 
```
import {enableLiveReload} from 'electron-compile';
enableLiveReload();
```
5. `npm start`

**Comment by kneumei** [comment]
Follow up: 

I did some digging around in electron-forge and found that if I do this in package.config and run `npm start`, things work for me. 

```
  "main": "src/main.js",
  "scripts": {
    "start": "node ./node_modules/electron-prebuilt-compile/lib/cli.js ."
  },
```

**Comment by Knaackee** [comment]
I got the same error, but this does not help.

**Comment by isekaimaou1109** [comment]
yeah me too, need help !! tks in advanced

**Comment by chadbr** [comment]
@isekaimaou1109 this project is deprecated...

![image](https://user-images.githubusercontent.com/3179452/76440341-b5cdf880-638b-11ea-84de-7b65d02052e6.png)

https://github.com/electron-userland/electron-compile/blob/master/README.md

**Comment by isekaimaou1109** [comment]
> @isekaimaou1109 this project is deprecated...
> 
> ![image](https://user-images.githubusercontent.com/3179452/76440341-b5cdf880-638b-11ea-84de-7b65d02052e6.png)
> 
> https://github.com/electron-userland/electron-compile/blob/master/README.md

ok i understood and tks
