### ISSUE TITLE
Cant find module reset-search-paths

### ISSUE THREAD

**Issue by burtonator** [electron-userland/electron-compile#305]
I'm getting the following on startup.  

I have it working in a new / isolated setup but when I move to install electron-prebuilt-compile in my main project it fails. 

```A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/home/burton/projects/polar-bookshelf'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/burton/projects/polar-bookshelf/node_modules/electron-prebuilt-compile/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at init (/home/burton/projects/polar-bookshelf/node_modules/electron-compile/lib/config-parser.js:294:16)
    at main (/home/burton/projects/polar-bookshelf/node_modules/electron-prebuilt-compile/lib/es6-init.js:58:29)
    at Object.<anonymous> (/home/burton/projects/polar-bookshelf/node_modules/electron-prebuilt-compile/lib/es6-init.js:61:1)
    at Object.<anonymous> (/home/burton/projects/polar-bookshelf/node_modules/electron-prebuilt-compile/lib/es6-init.js:63:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
^C
```

**Comment by burtonator** [comment]
closing this .. removing .cache directoriy fixed it.
