### ISSUE TITLE
What's the currently recommended way to package an electron-compile app?

### ISSUE THREAD

**Issue by dfeinzeig** [electron-userland/electron-compile#322]
I've built an app using electron-compile and now I need a Windows package to distribute. What are my options? Seems like most of the discussion related to this is old. Is there an example or some docs somewhere on this? Thanks!

**Comment by dfeinzeig** [comment]
I tried running the compile command, but I get an error:

`9 verbose lifecycle videahealth-videadetect@0.1.0~compile-cache: CWD: /mnt/c/Users/David/Documents/code/videahealth/desk
top-application
10 silly lifecycle videahealth-videadetect@0.1.0~compile-cache: Args: [ '-c',
10 silly lifecycle   'electron-compile -a /mnt/c/Users/David/Documents/code/videahealth/desktop-application/' ]
11 silly lifecycle videahealth-videadetect@0.1.0~compile-cache: Returned: code: 255  signal: null
12 info lifecycle videahealth-videadetect@0.1.0~compile-cache: Failed to exec compile-cache script
13 verbose stack Error: videahealth-videadetect@0.1.0 compile-cache: `electron-compile -a /mnt/c/Users/David/Documents/c
ode/videahealth/desktop-application/`
13 verbose stack Exit status 255
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:1
4)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid videahealth-videadetect@0.1.0
15 verbose cwd /mnt/c/Users/David/Documents/code/videahealth/desktop-application
16 verbose Linux 4.4.0-17134-Microsoft
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "compile-cache"
18 verbose node v10.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 255
22 error videahealth-videadetect@0.1.0 compile-cache: `electron-compile -a /mnt/c/Users/David/Documents/code/videahealth/desktop-application/`
22 error Exit status 255
23 error Failed at the videahealth-videadetect@0.1.0 compile-cache script.`
